api_version: go1
runtime: go

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /albums(.*)
  script: _go_app

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /css
  static_dir: static/css

- url: /kids(.*)
  script: _go_app

- url: /test/proxy
  script: _go_app
  login: admin

- url: /test/(.*)
  script: _go_app

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /pubs
  static_dir: pubs

- url: /talks
  static_dir: talks
