application: ian-rose
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: static/css

- url: /docs
  static_dir: docs

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /ports(.*)
  script: ip_redirect.app

- url: /pubs
  static_dir: pubs

- url: /talks
  static_dir: talks
