application: ian-rose
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /albums(.*)
  script: main.app

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /testing/
  static_dir: static/testing

- url: /css
  static_dir: static/css

- url: /docs
  static_dir: docs

- url: /kids(.*)
  script: main.app

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /ports(.*)
  script: ip_redirect.app

- url: /pubs
  static_dir: pubs

- url: /talks
  static_dir: talks

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
