// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package storage

import (
	"time"
)

type StravaToken struct {
	Username     string
	AccessToken  string
	RefreshToken string
	CreatedTime  time.Time
	ExpiresAt    time.Time
}
