name: My Comment Tester

on:
  issue_comment:
    types: [created, edited]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hi there' && echo ${{ github.event.comment.body }}
