# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build
      run: make build

    - name: Test
      run: go test ./...

  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: mkdir -p bin/linux && cp bin/webapp bib/linux_amd64/webapp
        
      - name: Get shortsha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Push to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          registry: gcr.io
          project_id: ian-rose
          image_name: us-central1-docker.pkg.dev/ian-rose/docker-1/webapp
          image_tag: latest,${{ steps.vars.outputs.sha_short }}
